# Base configs
#url: "https://simad.github.io"
baseurl: "/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: ""

# Collection settings
collections:
  - photos

  - sections

# UI configs
title: "Chasing Wolves Photography"
subtitle: ""
author: "Silvia"
header:
 title: "Chasing Wolves"
 subtitle: "Photography Project"
web_design: "Silvia"

social:
  - name: Instagram
    icon: instagram
    username: chasingwolves.photography
    url: https://www.instagram.com/chasingwolves.photography
    desc: Follow me on Instagram
    share: false

  - name: Twitter
    icon: twitter
    username: silmnd
    url: https://www.twitter.com/silmnd
    desc: Follow me on Twitter
    share: true

  - name: Email
    icon: envelope-o
    username: silvia@divisionbyzero.co
    url: mailto:silvia@divisionbyzero.co
    desc: Shoot me an Email
    share: false