# Base configs
baseurl: "https://simad.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: ""

# UI configs
title: "Photography by Silvia"
subtitle: ""
author: "Silvia"
header:
 title: "PATTERNS"
 subtitle: "by Silvia"
footer:
 name: "Something"
 bio: "Something something."
 github: "github"
web_design: "AJ"
social_urls:
#  facebook: "https://www.facebook.com/ramswaroop"
#  twitter: "https://www.twitter.com/ramswarooppatra"
#  instagram: "https://www.instagram.com/ramswarooppatra"
#  dribbble: "https://dribbble.com/ramswaroop"
#  linkedin: "https://in.linkedin.com/in/ramswarooppatra"
#  github: "https://www.github.com/ramswaroop"
